/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const TabIndexLazyImport = createFileRoute('/tab/')()
const SignUpIndexLazyImport = createFileRoute('/sign-up/')()
const SignInIndexLazyImport = createFileRoute('/sign-in/')()
const MakeYourOwnIndexLazyImport = createFileRoute('/make-your-own/')()
const ExecutivesIndexLazyImport = createFileRoute('/executives/')()
const DashboardIndexLazyImport = createFileRoute('/dashboard/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TabIndexLazyRoute = TabIndexLazyImport.update({
  id: '/tab/',
  path: '/tab/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tab/index.lazy').then((d) => d.Route))

const SignUpIndexLazyRoute = SignUpIndexLazyImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign-up/index.lazy').then((d) => d.Route))

const SignInIndexLazyRoute = SignInIndexLazyImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign-in/index.lazy').then((d) => d.Route))

const MakeYourOwnIndexLazyRoute = MakeYourOwnIndexLazyImport.update({
  id: '/make-your-own/',
  path: '/make-your-own/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/make-your-own/index.lazy').then((d) => d.Route),
)

const ExecutivesIndexLazyRoute = ExecutivesIndexLazyImport.update({
  id: '/executives/',
  path: '/executives/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/executives/index.lazy').then((d) => d.Route),
)

const DashboardIndexLazyRoute = DashboardIndexLazyImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/executives/': {
      id: '/executives/'
      path: '/executives'
      fullPath: '/executives'
      preLoaderRoute: typeof ExecutivesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/make-your-own/': {
      id: '/make-your-own/'
      path: '/make-your-own'
      fullPath: '/make-your-own'
      preLoaderRoute: typeof MakeYourOwnIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/tab/': {
      id: '/tab/'
      path: '/tab'
      fullPath: '/tab'
      preLoaderRoute: typeof TabIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardIndexLazyRoute
  '/executives': typeof ExecutivesIndexLazyRoute
  '/make-your-own': typeof MakeYourOwnIndexLazyRoute
  '/sign-in': typeof SignInIndexLazyRoute
  '/sign-up': typeof SignUpIndexLazyRoute
  '/tab': typeof TabIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardIndexLazyRoute
  '/executives': typeof ExecutivesIndexLazyRoute
  '/make-your-own': typeof MakeYourOwnIndexLazyRoute
  '/sign-in': typeof SignInIndexLazyRoute
  '/sign-up': typeof SignUpIndexLazyRoute
  '/tab': typeof TabIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/executives/': typeof ExecutivesIndexLazyRoute
  '/make-your-own/': typeof MakeYourOwnIndexLazyRoute
  '/sign-in/': typeof SignInIndexLazyRoute
  '/sign-up/': typeof SignUpIndexLazyRoute
  '/tab/': typeof TabIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/executives'
    | '/make-your-own'
    | '/sign-in'
    | '/sign-up'
    | '/tab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/executives'
    | '/make-your-own'
    | '/sign-in'
    | '/sign-up'
    | '/tab'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/executives/'
    | '/make-your-own/'
    | '/sign-in/'
    | '/sign-up/'
    | '/tab/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
  ExecutivesIndexLazyRoute: typeof ExecutivesIndexLazyRoute
  MakeYourOwnIndexLazyRoute: typeof MakeYourOwnIndexLazyRoute
  SignInIndexLazyRoute: typeof SignInIndexLazyRoute
  SignUpIndexLazyRoute: typeof SignUpIndexLazyRoute
  TabIndexLazyRoute: typeof TabIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
  ExecutivesIndexLazyRoute: ExecutivesIndexLazyRoute,
  MakeYourOwnIndexLazyRoute: MakeYourOwnIndexLazyRoute,
  SignInIndexLazyRoute: SignInIndexLazyRoute,
  SignUpIndexLazyRoute: SignUpIndexLazyRoute,
  TabIndexLazyRoute: TabIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard/",
        "/executives/",
        "/make-your-own/",
        "/sign-in/",
        "/sign-up/",
        "/tab/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.lazy.tsx"
    },
    "/executives/": {
      "filePath": "executives/index.lazy.tsx"
    },
    "/make-your-own/": {
      "filePath": "make-your-own/index.lazy.tsx"
    },
    "/sign-in/": {
      "filePath": "sign-in/index.lazy.tsx"
    },
    "/sign-up/": {
      "filePath": "sign-up/index.lazy.tsx"
    },
    "/tab/": {
      "filePath": "tab/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
